name: Docs Deploy

# Gatilho: Roda sempre que você fizer push na branch 'main'
on:
  push:
    branches: ["main"]

# Permissões necessárias para o robô escrever na branch gh-pages
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o seu código do repositório
      - uses: actions/checkout@v4

      # 2. Instala o Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3. Instala as dependências de documentação E a sua própria biblioteca
      - name: Install dependencies
        run: |
          pip install sphinx sphinx-rtd-theme
          pip install .  # Instala a SciMagnet/Smilum para o Sphinx ler as docstrings

      # 4. Entra na pasta docs e constrói o HTML
      - name: Build Sphinx Docs
        run: |
          cd docs
          make html

      # 5. Publica o conteúdo da pasta html na branch 'gh-pages'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html